### ISSUE TITLE
page shows README

### ISSUE THREAD

**Issue by madurner** [StartBootstrap/startbootstrap-resume#202]
I am new to bootstrap and wanted to start by forking this repo and rename it (to madurner.github.io) so it turns to be my user page. In the next step, I wanted to start changing the `dist/index.html`.
The problem now is, that looking at my [page](https://madurner.github.io/) it seems to prompt the README.md file (at least changes in there are also present on the page). What do I have to change, to get the "real" template shown? Thx

**Comment by sagarnayak** [comment]
how did you fix this ?
