### ISSUE TITLE
Versions not aligned with tags

### ISSUE THREAD

**Issue by craigh** [StartBootstrap/startbootstrap-resume#203]
https://startbootstrap.com/themes/resume/ and https://github.com/StartBootstrap/startbootstrap-resume/blob/master/package.json#L4 shows this is version 6.0.1

https://github.com/StartBootstrap/startbootstrap-resume/tags shows this is version 5.0.8

could you please align the github tags with your version?

**Comment by davidtmiller** [comment]
Should be fixed now in the latest push
