### ISSUE TITLE
is there a reference for icons for the skills tab?

### ISSUE THREAD

**Issue by CarmineCodes** [StartBootstrap/startbootstrap-resume#227]
im using this template and working on adding my programming languages and im looking to add c# and c++ and wondering if theres a reference guide for all the available icons that can be used?

**Comment by Kerveyfelix** [comment]
A reference guide is not available as of now.

**Comment by codelover96** [comment]
Is it possible to generate icons for other languages/frameworks?

**Comment by kerry-tarrant** [comment]
This would be a helpful feature. btw, this a beautiful theme. Thank you for sharing it!

**Comment by kerry-tarrant** [comment]
Looking at some of the HTML file, it looks like the icons under the skills section are being pulled from fontawesome [dot] com. You should checkout the site and see whatever is relevant to you. Some of the icons are premium, but they have a wide selection and make it pretty easy. Once you have an icon picked out, like Python for example, you'll be able to paste text that looks like this <i class="fab fa-python"></i> into your HTML file. Though I wasn't able to find an icon for C++. This seems to be a criticism of fontawesome. But see the workarounds given in this issue section https://github.com/FortAwesome/Font-Awesome/issues/14021.

Let me know if you have any questions about this.

**Comment by codelover96** [comment]
I'll have a look into it. Thanks.
