### ISSUE TITLE
Dowload my CV button

### ISSUE THREAD

**Issue by danybr0** [StartBootstrap/startbootstrap-resume#234]
It just an idea but wouldn't be nice to have a download my CV button between the short description and the social links? The goal should be to download your CV in pdf format. An example of such a button: http://104.131.177.38/demo/wp/iamx/home-two/#skills

**Comment by madurner** [comment]
You can easily add such a button by your own. Just load up a cv-pdf to e.g. the `assets/`dir and add some like this:                         `<a class="social-icon" href="assets/[name of your cv file].pdf"><i class="fas fa-id-card"></i></a>` (the icon is just an example) [here](https://github.com/StartBootstrap/startbootstrap-resume/blob/d58df1ef433af03b754c942b72ca364a4a8385bc/dist/index.html#L55). This should do all the magic.
