### ISSUE TITLE
Browser Sync doesn't work, issue Pug rendering to HTML

### ISSUE THREAD

**Issue by pieterjanplessers** [StartBootstrap/startbootstrap-resume#249]
Whenever I run the app with `npm start`, the latest changes to the Pug file(s) are being rendered and build into /dist. That's good, as intended. As soon as I start changing code in the Pug file(s), the Browser Sync seems not to be working. It doesn't auto sync the browser page to the latest changes. Only when I `Terminate batch job` and re-run the `npm start` command.
Is this how it is intended or am I missing something?

**Comment by davidtmiller** [comment]
Upath has been added to the npm scripts to work for windows machines, so this should be working now!

**Comment by pieterjanplessers** [comment]
Hi David, thank you. Will be testing that today!
