### ISSUE TITLE
All but One of My Hamburger Menu Links are Working

### ISSUE THREAD

**Issue by Metaflex** [StartBootstrap/startbootstrap-resume#251]
(New to Coding) I can navigate to any of my other sections of my website using tabs in my hamburger menu, but one tab in particular doesn't respond at all. i don't know if it makes a difference but on this tab in particular there is a carousel. I dont even know where to begin in order to fix this issue myself. If anyone can please help me out I'd really appreciate it.
this is how i set up that one section.

 <hr class="m-0">

    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="#GraphicDesignWork">
      <div class="w-100">
        <h2 class="mb-5">Graphic Design Work</h2>
        
        <div id="#GDCarousel" class="carousel slide" data-ride="carousel" data-interval="2500">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-100" src="img/Slide1.jpg" alt="First Slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="img/Slide2.jpg" alt="Second Slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="img/Slide3.jpg" alt="Third Slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="img/Slide4.jpg" alt="Fourth Slide">
              </div>         
            </div>
            <a class="carousel-control-prev" href="#GDCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#GDCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
          </div>

          
    </section>

**Comment by dariocurr** [comment]
Maybe the problem is that you didn't add the js dependencies, which bootstrap carousel requires:
Try to add the following two scripts:

```
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
```
