### ISSUE TITLE
I can't change hte page title

### ISSUE THREAD

**Issue by Boratsu** [StartBootstrap/startbootstrap-resume#257]
L.S.

It seems that regardless of my title in HTML code the page title is hard coded to "Resume - Start Bootstrap Theme". Where do I change this? 

Below my code (unchanged except for tile). 

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>MEC Oegstgeest · Mijn Eigen Computer</title>

  
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  
  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet">

  
  <link href="css/resume.min.css" rel="stylesheet">

</head>

**Comment by Boratsu** [comment]
I dont know why but now it changed. Maybe because there was an old index.html and an index.php in the site folder.

**Comment by GASOLINE** [comment]
Cache
